version: "3.7"

services:
  webserver:
    image: nginx:latest
    container_name: dream_dgx
    ports:
      - 8091:80
    volumes:
      - ../:/var/www/html
      - ../webserver/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: ../webserver
    volumes:
      - ../:/var/www/html